const getters = {
  sidebar: state => state.app.sidebar,
  token: state => state.user.token,
  device: state => state.app.device,
  avatar: state => state.user.avatar,
  userId: state => state.user.userId,
  supplierId: state => state.user.supplierId,
  userInfo: state => state.user.userInfo,
  name: state => state.user.name,
  parentOrgId: state => state.user.parentOrgId,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  permission_decimal: state => state.permission.decimalVal,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  permissions: state => state.user.permissions,
  menuState: state => state.chemicalInfo.menuState,
  msgCount: state => state.user.msgCount,
  deptId: state => state.user.deptId,
  supplierParams: state => state.listParams.supplierList,
  commonTag: state => state.listParams.commonTag,
  assistInfo: state => state.listParams.assistInfo,
  unsettled: state => state.listParams.unsettled,
  orgManager: state => state.user.orgManager,
}
export default getters
