export function orderListData() {
  return [
    {
      name:'销售订单',
      key:'sellOrderNum',
      show:false,
      value:null,
      orderList:[
        {
          key:'orderStateOrYes',
          name:'已完成',
          value:null
        },
        {
          key:'orderStateOrNo',
          name:'未完成',
          value:null
        }
      ]
    },
    {
      name:'成衣采购订单',
      key:'cyPurchaseNum',
      show:false,
      value:null,
      orderList:[
        {
          key:'cyPurchaseStateNum',
          name:'已完成',
          value:null
        },
        {
          key:'cySupplierSureNum',
          name:'未确认',
          value:null
        },
        {
          key:'cyPurchaseProdNum',
          name:'生产中',
          value:null
        }
      ],
    },
    {
      name:'光坯采购订单',
      key:'gpPurchaseNum',
      show:false,
      value:null,
      orderList:[
        {
          key:'gpPurchaseStateNum',
          name:'已完成',
          value:null
        },
        {
          key:'gpSupplierSureNum',
          name:'未确认',
          value:null
        },
        {
          key:'gpPurchaseProdNum',
          name:'生产中',
          value:null
        }
      ],
    },
    {
      name:'毛坯采购订单',
      key:'mpPurchaseNum',
      show:false,
      value:null,
      orderList:[
        {
          key:'mpPurchaseStateNum',
          name:'已完成',
          value:null
        },
        {
          key:'mpSupplierSureNum',
          name:'未确认',
          value:null
        },
        {
          key:'mpPurchaseProdNum',
          name:'生产中',
          value:null
        }
      ],
    },
    {
      name:'棉纱采购订单',
      key:'spPurchaseNum',
      show:false,
      value:null,
      orderList:[
        {
          key:'spPurchaseStateNum',
          name:'已完成',
          value:null
        },
        {
          key:'spSupplierSureNum',
          name:'未确认',
          value:null
        },
        {
          key:'spPurchaseProdNum',
          name:'生产中',
          value:null
        }
      ],
    },
    {
      name:'辅料采购订单',
      show:false,
      key:'flPurchaseNum',
      value:null,
      orderList:[
        {
          key:'flPurchaseStateNum',
          name:'已完成',
          value:null
        },
        {
          key:'flSupplierSureNum',
          name:'未确认',
          value:null
        },
        {
          key:'flPurchaseProdNum',
          name:'生产中',
          value:null
        }
      ],
    }
  ]
}